/*
 * Etiquetas.java
 *
 * Created on 29 de Agosto de 2007, 16:15
 */

package takttime;

import java.io.File;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/**
 *
 * @author  administrator
 */
public class Etiquetas extends javax.swing.JFrame {
    boolean ok = true;    
    /** Creates new form Etiquetas */
    public Etiquetas() {
        initComponents();
        setLocationRelativeTo(null);        
        
        jTxtInicio.setDocument(new FixedLengthDocument(7));
        jTxtFim.setDocument(new FixedLengthDocument(7));        
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Código Gerado ">//GEN-BEGIN:initComponents
    private void initComponents() {
        jBtnGerar = new javax.swing.JButton();
        jTxtInicio = new javax.swing.JTextField();
        jTxtFim = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTxtPath = new javax.swing.JTextField();
        jAbrir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        jBtnGerar.setMnemonic('G');
        jBtnGerar.setText("Gerar");
        jBtnGerar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnGerarActionPerformed(evt);
            }
        });

        jTxtInicio.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTxtInicio.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTxtInicioKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTxtInicioKeyTyped(evt);
            }
        });

        jTxtFim.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTxtFim.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTxtFimKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTxtFimKeyTyped(evt);
            }
        });

        jLabel1.setText("In\u00edcio");

        jLabel2.setText("Fim");

        jTxtPath.setEditable(false);

        jAbrir.setText("...");
        jAbrir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jAbrirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jTxtInicio, javax.swing.GroupLayout.DEFAULT_SIZE, 76, Short.MAX_VALUE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jTxtFim, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(16, 16, 16))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jBtnGerar)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jTxtPath, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jAbrir, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTxtInicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTxtFim, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(26, 26, 26)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTxtPath, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jAbrir))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                .addComponent(jBtnGerar)
                .addContainerGap())
        );
        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jAbrirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jAbrirActionPerformed
// TODO adicione seu código de manipulação aqui:
        JFileChooser arq= new JFileChooser();
        int Result=arq.showSaveDialog(this);
        if(Result==JFileChooser.APPROVE_OPTION){
            File arquivo= arq.getSelectedFile(); //Classe para Arquivos
            jTxtPath.setText(arquivo.getPath()); //Imprime nome do Arquivo
        }        
    }//GEN-LAST:event_jAbrirActionPerformed

    private void jBtnGerarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnGerarActionPerformed
// TODO adicione seu código de manipulação aqui:
        if (jTxtPath.getText().equals("") || jTxtInicio.getText().equals("") || jTxtFim.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Preencha os campos!");
        } else {
            
            int in = Integer.parseInt(jTxtInicio.getText());
            int fi = Integer.parseInt(jTxtFim.getText());
            exportCodeBar exCodeBar = new exportCodeBar(
                jTxtPath.getText(), in, fi, "08");
            exCodeBar.exporta();
        
            JOptionPane.showMessageDialog(null, "Etiquetas Geradas!");
            JOptionPane.showMessageDialog(null, jTxtPath.getText());
        
            dispose();            
        }
    }//GEN-LAST:event_jBtnGerarActionPerformed

    private void jTxtFimKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTxtFimKeyPressed
// TODO adicione seu código de manipulação aqui:
        int code = evt.getKeyCode();
        if ((code>95 && code<106) || (code==8) || (code>47 && code<58)) {
            ok = true;
        } else {
            ok = false;
        }        
    }//GEN-LAST:event_jTxtFimKeyPressed

    private void jTxtInicioKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTxtInicioKeyPressed
// TODO adicione seu código de manipulação aqui:
        int code = evt.getKeyCode();
        if ((code>95 && code<106) || (code==8) || (code>47 && code<58)) {
            ok = true;
        } else {
            ok = false;
        }        
    }//GEN-LAST:event_jTxtInicioKeyPressed

    private void jTxtFimKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTxtFimKeyTyped
// TODO adicione seu código de manipulação aqui:
        if (!ok){  
            evt.consume();
        }        
    }//GEN-LAST:event_jTxtFimKeyTyped

    private void jTxtInicioKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTxtInicioKeyTyped
// TODO adicione seu código de manipulação aqui:
        if (!ok){  
            evt.consume();  
        }
    }//GEN-LAST:event_jTxtInicioKeyTyped
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Etiquetas().setVisible(true);
            }
        });
    }
    
    // Declaração de variáveis - não modifique//GEN-BEGIN:variables
    private javax.swing.JButton jAbrir;
    private javax.swing.JButton jBtnGerar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField jTxtFim;
    private javax.swing.JTextField jTxtInicio;
    private javax.swing.JTextField jTxtPath;
    // Fim da declaração de variáveis//GEN-END:variables
    
}
