/*
 * MenuTakt.java
 *
 * Created on 5 de Outubro de 2007, 10:54
 */

package takttime;

import java.awt.Image;
import java.awt.Toolkit;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.KeyEvent;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.GregorianCalendar;
import javax.swing.JDialog;
import javax.swing.JOptionPane;
import javax.swing.SwingConstants;
import javax.swing.UIManager;
import javax.swing.Timer;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;


/**
 *
 * @author  administrator
 */
public class MenuTakt extends javax.swing.JFrame {
    boolean ok = true;
    SimpleDateFormat dtFormat = new SimpleDateFormat("dd/MM/yyyy");
    SimpleDateFormat hrFormat = new SimpleDateFormat("HH:mm:ss");
    //SimpleDateFomrat takt = new SimpleDateFormat("HH:mm:ss");
    
    /** Creates new form MenuTakt */
    public MenuTakt() {
        
        setIconImage(Toolkit.getDefaultToolkit().createImage("/images/iconAlbert32.png"));
        try {   
            UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());   
        }   
        catch (Exception e) {}  

        initComponents();
        
        setExtendedState(MAXIMIZED_BOTH);  

        Timer t = new Timer(1000, new ActionListener(){
            public void actionPerformed(ActionEvent e){
                mostraData();
                mostraHora();
                //atualizarHoras();
            }
            
        });
        t.setInitialDelay(0);
        t.setRepeats(true);
        t.start();
        
        jTxtCodigoBarra.setDocument(new FixedLengthDocument(13));
        jTxtCodigoFind.setDocument(new FixedLengthDocument(13));
        
        DefaultTableCellRenderer renderer = new DefaultTableCellRenderer();
        renderer.setHorizontalAlignment(SwingConstants.CENTER);
        jTblFindOF.getColumnModel().getColumn(0).setCellRenderer(renderer);
        jTblFindOF.getColumnModel().getColumn(1).setCellRenderer(renderer);
        jTblFindOF.getColumnModel().getColumn(2).setCellRenderer(renderer);        
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Código Gerado ">//GEN-BEGIN:initComponents
    private void initComponents() {
        jDesktopPane = new javax.swing.JDesktopPane();
        jIFraTime = new javax.swing.JInternalFrame();
        jLabel1 = new javax.swing.JLabel();
        jTxtCodigoBarra = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jTxtData = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTxtHora = new javax.swing.JTextField();
        jBtnFechar = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLblImage = new javax.swing.JLabel();
        jIFraFind = new javax.swing.JInternalFrame();
        jPanel3 = new javax.swing.JPanel();
        jLblImage1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTblFindOF = new javax.swing.JTable();
        jBtnFechar1 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jTxtCodigoFind = new javax.swing.JTextField();
        jBtnFind = new javax.swing.JButton();
        jTxtTaktTime = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jIFraCalculo = new javax.swing.JInternalFrame();
        jPanel4 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jTxtDemanda = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jTxtHora1 = new javax.swing.JTextField();
        jBtnCalcular = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel8 = new javax.swing.JLabel();
        jTxtTaktPadrao = new javax.swing.JTextField();
        jBtnClose = new javax.swing.JButton();
        jPnlStatus = new javax.swing.JPanel();
        jBandAtivo = new javax.swing.JLabel();
        jBandConexao = new javax.swing.JLabel();
        jBandDataHora = new javax.swing.JLabel();
        jToolBar2 = new javax.swing.JToolBar();
        jBtnSair = new javax.swing.JButton();
        jToolBar1 = new javax.swing.JToolBar();
        jBtnTaktTime = new javax.swing.JButton();
        jBtnTaktFind = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jMenuBar = new javax.swing.JMenuBar();
        jMnuPrograma = new javax.swing.JMenu();
        jMnuTaktTime = new javax.swing.JMenuItem();
        jMnuTaktFind = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JSeparator();
        jMnuSair = new javax.swing.JMenuItem();
        jMnuFerramentas = new javax.swing.JMenu();
        jMnuEtiquetas = new javax.swing.JMenuItem();
        jMnuCalculo = new javax.swing.JMenuItem();
        jMnuAjuda = new javax.swing.JMenu();
        jMnuAbout = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("TaktTime - Albert Form");
        jDesktopPane.setBackground(new java.awt.Color(204, 204, 204));
        jDesktopPane.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        try {
            jIFraTime.setSelected(true);
        } catch (java.beans.PropertyVetoException e1) {
            e1.printStackTrace();
        }
        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14));
        jLabel1.setText("C\u00f3digo de Barras");

        jTxtCodigoBarra.setFont(new java.awt.Font("Tahoma", 1, 14));
        jTxtCodigoBarra.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTxtCodigoBarraKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTxtCodigoBarraKeyTyped(evt);
            }
        });

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14));
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/week_f224.png")));
        jLabel2.setText("Data");

        jTxtData.setEditable(false);
        jTxtData.setFont(new java.awt.Font("Dialog", 1, 14));
        jTxtData.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14));
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/day_f224.png")));
        jLabel3.setText("Hora");

        jTxtHora.setEditable(false);
        jTxtHora.setFont(new java.awt.Font("Dialog", 1, 14));
        jTxtHora.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTxtData, javax.swing.GroupLayout.DEFAULT_SIZE, 97, Short.MAX_VALUE)
                    .addComponent(jTxtHora, javax.swing.GroupLayout.DEFAULT_SIZE, 97, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTxtData, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTxtHora, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jBtnFechar.setFont(new java.awt.Font("Tahoma", 1, 14));
        jBtnFechar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/exit24.png")));
        jBtnFechar.setMnemonic('F');
        jBtnFechar.setText("Fechar");
        jBtnFechar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnFecharActionPerformed(evt);
            }
        });

        jLblImage.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLblImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/form2.gif")));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLblImage)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLblImage)
        );

        javax.swing.GroupLayout jIFraTimeLayout = new javax.swing.GroupLayout(jIFraTime.getContentPane());
        jIFraTime.getContentPane().setLayout(jIFraTimeLayout);
        jIFraTimeLayout.setHorizontalGroup(
            jIFraTimeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jIFraTimeLayout.createSequentialGroup()
                .addGroup(jIFraTimeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jIFraTimeLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jIFraTimeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel1)
                            .addGroup(jIFraTimeLayout.createSequentialGroup()
                                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jBtnFechar, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jTxtCodigoBarra))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jIFraTimeLayout.setVerticalGroup(
            jIFraTimeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jIFraTimeLayout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTxtCodigoBarra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jIFraTimeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jBtnFechar, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jIFraTime.setBounds(0, 0, 330, 300);
        jDesktopPane.add(jIFraTime, javax.swing.JLayeredPane.DEFAULT_LAYER);

        try {
            jIFraFind.setSelected(true);
        } catch (java.beans.PropertyVetoException e1) {
            e1.printStackTrace();
        }
        jLblImage1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLblImage1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/form2.gif")));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLblImage1, javax.swing.GroupLayout.PREFERRED_SIZE, 396, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLblImage1)
        );

        jTblFindOF.setFont(new java.awt.Font("Tahoma", 1, 14));
        jTblFindOF.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Data", "Hora", "Setor"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTblFindOF.setEnabled(false);
        jTblFindOF.setShowHorizontalLines(false);
        jTblFindOF.setShowVerticalLines(false);
        jScrollPane1.setViewportView(jTblFindOF);

        jBtnFechar1.setFont(new java.awt.Font("Tahoma", 1, 14));
        jBtnFechar1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/exit24.png")));
        jBtnFechar1.setMnemonic('F');
        jBtnFechar1.setText("Fechar");
        jBtnFechar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnFechar1ActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14));
        jLabel4.setText("Codigo de Barra OF:");

        jTxtCodigoFind.setFont(new java.awt.Font("Tahoma", 1, 14));
        jTxtCodigoFind.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTxtCodigoFind.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTxtCodigoFindKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTxtCodigoFindKeyTyped(evt);
            }
        });

        jBtnFind.setFont(new java.awt.Font("Tahoma", 1, 14));
        jBtnFind.setText("...");
        jBtnFind.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnFindActionPerformed(evt);
            }
        });

        jTxtTaktTime.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        jTxtTaktTime.setEnabled(false);

        jLabel5.setText("TaktTime");

        javax.swing.GroupLayout jIFraFindLayout = new javax.swing.GroupLayout(jIFraFind.getContentPane());
        jIFraFind.getContentPane().setLayout(jIFraFindLayout);
        jIFraFindLayout.setHorizontalGroup(
            jIFraFindLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jIFraFindLayout.createSequentialGroup()
                .addGroup(jIFraFindLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jIFraFindLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jIFraFindLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addGroup(jIFraFindLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, 0, 386, Short.MAX_VALUE)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jIFraFindLayout.createSequentialGroup()
                                    .addComponent(jTxtCodigoFind, javax.swing.GroupLayout.PREFERRED_SIZE, 353, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jBtnFind, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addComponent(jPanel3, 0, 410, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jIFraFindLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTxtTaktTime, javax.swing.GroupLayout.DEFAULT_SIZE, 240, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jBtnFechar1)))
                .addContainerGap())
        );
        jIFraFindLayout.setVerticalGroup(
            jIFraFindLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jIFraFindLayout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jIFraFindLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTxtCodigoFind, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBtnFind))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jIFraFindLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBtnFechar1, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(jTxtTaktTime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(24, Short.MAX_VALUE))
        );
        jIFraFind.setBounds(0, 0, 430, 360);
        jDesktopPane.add(jIFraFind, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jIFraCalculo.setMaximizable(true);
        jIFraCalculo.setTitle("Calculo de TaktTime");
        try {
            jIFraCalculo.setSelected(true);
        } catch (java.beans.PropertyVetoException e1) {
            e1.printStackTrace();
        }
        jPanel4.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14));
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/formulario1.png")));
        jLabel6.setText("Demanda/Unidade");

        jTxtDemanda.setFont(new java.awt.Font("Dialog", 1, 14));
        jTxtDemanda.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTxtDemanda.setEnabled(false);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14));
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/edittime24.png")));
        jLabel7.setText("Clock Di\u00e1rio/Horas");

        jTxtHora1.setFont(new java.awt.Font("Dialog", 1, 14));
        jTxtHora1.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTxtHora1.setEnabled(false);

        jBtnCalcular.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/calc24.png")));
        jBtnCalcular.setMnemonic('C');
        jBtnCalcular.setText("Calcular");
        jBtnCalcular.setEnabled(false);
        jBtnCalcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnCalcularActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14));
        jLabel8.setText("TaktTime Padr\u00e3o");

        jTxtTaktPadrao.setEditable(false);
        jTxtTaktPadrao.setFont(new java.awt.Font("Tahoma", 1, 14));

        jBtnClose.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/exit16.png")));
        jBtnClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnCloseActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addComponent(jTxtTaktPadrao, javax.swing.GroupLayout.DEFAULT_SIZE, 326, Short.MAX_VALUE)
                    .addComponent(jSeparator2, javax.swing.GroupLayout.DEFAULT_SIZE, 326, Short.MAX_VALUE)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel7)
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTxtHora1)
                            .addComponent(jTxtDemanda, javax.swing.GroupLayout.DEFAULT_SIZE, 59, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jBtnCalcular))
                    .addComponent(jBtnClose, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTxtDemanda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(jTxtHora1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(jBtnCalcular)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTxtTaktPadrao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jBtnClose)
                .addGap(52, 52, 52))
        );

        javax.swing.GroupLayout jIFraCalculoLayout = new javax.swing.GroupLayout(jIFraCalculo.getContentPane());
        jIFraCalculo.getContentPane().setLayout(jIFraCalculoLayout);
        jIFraCalculoLayout.setHorizontalGroup(
            jIFraCalculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jIFraCalculoLayout.setVerticalGroup(
            jIFraCalculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        jIFraCalculo.setBounds(20, 10, 360, 210);
        jDesktopPane.add(jIFraCalculo, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jPnlStatus.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jBandAtivo.setText(" Ativo: Menu Principal");
        jBandAtivo.setAutoscrolls(true);
        jBandAtivo.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jBandConexao.setText(" Conectado ao Servidor: 192.168.0.100  Usu\u00e1rio: admin  Porta: 5432");
        jBandConexao.setAutoscrolls(true);
        jBandConexao.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jBandDataHora.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jBandDataHora.setAutoscrolls(true);
        jBandDataHora.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        javax.swing.GroupLayout jPnlStatusLayout = new javax.swing.GroupLayout(jPnlStatus);
        jPnlStatus.setLayout(jPnlStatusLayout);
        jPnlStatusLayout.setHorizontalGroup(
            jPnlStatusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPnlStatusLayout.createSequentialGroup()
                .addComponent(jBandAtivo, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jBandConexao, javax.swing.GroupLayout.DEFAULT_SIZE, 410, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jBandDataHora, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPnlStatusLayout.setVerticalGroup(
            jPnlStatusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPnlStatusLayout.createSequentialGroup()
                .addGroup(jPnlStatusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPnlStatusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jBandAtivo, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jBandConexao, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jBandDataHora, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jBtnSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/exit24.png")));
        jBtnSair.setMnemonic('r');
        jBtnSair.setText("Sair");
        jBtnSair.setBorderPainted(false);
        jBtnSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnSairActionPerformed(evt);
            }
        });

        jToolBar2.add(jBtnSair);

        jBtnTaktTime.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/day_f224.png")));
        jBtnTaktTime.setBorderPainted(false);
        jBtnTaktTime.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnTaktTimeActionPerformed(evt);
            }
        });

        jToolBar1.add(jBtnTaktTime);

        jBtnTaktFind.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/search_f224.png")));
        jBtnTaktFind.setBorderPainted(false);
        jBtnTaktFind.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnTaktFindActionPerformed(evt);
            }
        });

        jToolBar1.add(jBtnTaktFind);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/print24.png")));
        jButton1.setDisabledIcon(new javax.swing.ImageIcon(getClass().getResource("/images/printof.png")));
        jButton1.setEnabled(false);
        jToolBar1.add(jButton1);

        jMnuPrograma.setMnemonic('P');
        jMnuPrograma.setText("Programa");
        jMnuTaktTime.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/day_f216.png")));
        jMnuTaktTime.setMnemonic('T');
        jMnuTaktTime.setText("TaktTime");
        jMnuTaktTime.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMnuTaktTimeActionPerformed(evt);
            }
        });

        jMnuPrograma.add(jMnuTaktTime);

        jMnuTaktFind.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/search_f216.png")));
        jMnuTaktFind.setMnemonic('F');
        jMnuTaktFind.setText("TaktFind");
        jMnuTaktFind.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMnuTaktFindActionPerformed(evt);
            }
        });

        jMnuPrograma.add(jMnuTaktFind);

        jMnuPrograma.add(jSeparator1);

        jMnuSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/exit16b.png")));
        jMnuSair.setMnemonic('r');
        jMnuSair.setText("Sair");
        jMnuSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMnuSairActionPerformed(evt);
            }
        });

        jMnuPrograma.add(jMnuSair);

        jMenuBar.add(jMnuPrograma);

        jMnuFerramentas.setMnemonic('F');
        jMnuFerramentas.setText("Ferramentas");
        jMnuEtiquetas.setText("Gerar Etiquetas");
        jMnuEtiquetas.setEnabled(false);
        jMnuEtiquetas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMnuEtiquetasActionPerformed(evt);
            }
        });

        jMnuFerramentas.add(jMnuEtiquetas);

        jMnuCalculo.setMnemonic('C');
        jMnuCalculo.setText("C\u00e1lculo de Demanda");
        jMnuCalculo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMnuCalculoActionPerformed(evt);
            }
        });

        jMnuFerramentas.add(jMnuCalculo);

        jMenuBar.add(jMnuFerramentas);

        jMnuAjuda.setMnemonic('A');
        jMnuAjuda.setText("Ajuda");
        jMnuAbout.setMnemonic('b');
        jMnuAbout.setText("About");
        jMnuAjuda.add(jMnuAbout);

        jMenuBar.add(jMnuAjuda);

        setJMenuBar(jMenuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jToolBar2, javax.swing.GroupLayout.DEFAULT_SIZE, 577, Short.MAX_VALUE))
            .addComponent(jPnlStatus, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jDesktopPane, javax.swing.GroupLayout.DEFAULT_SIZE, 683, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jToolBar1, 0, 0, Short.MAX_VALUE)
                    .addComponent(jToolBar2, javax.swing.GroupLayout.PREFERRED_SIZE, 26, Short.MAX_VALUE))
                .addGap(2, 2, 2)
                .addComponent(jDesktopPane, javax.swing.GroupLayout.DEFAULT_SIZE, 365, Short.MAX_VALUE)
                .addGap(2, 2, 2)
                .addComponent(jPnlStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBtnCalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnCalcularActionPerformed
// TODO adicione seu código de manipulação aqui:
    }//GEN-LAST:event_jBtnCalcularActionPerformed

    private void jMnuEtiquetasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMnuEtiquetasActionPerformed
// TODO adicione seu código de manipulação aqui:
    }//GEN-LAST:event_jMnuEtiquetasActionPerformed

    private void jBtnCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnCloseActionPerformed
// TODO adicione seu código de manipulação aqui:
        jIFraCalculo.setVisible(false);
    }//GEN-LAST:event_jBtnCloseActionPerformed

    private void jMnuCalculoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMnuCalculoActionPerformed
// TODO adicione seu código de manipulação aqui:
        jIFraCalculo.setVisible(true);
    }//GEN-LAST:event_jMnuCalculoActionPerformed

    private void jBtnTaktFindActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnTaktFindActionPerformed
// TODO adicione seu código de manipulação aqui:
        taktFind();
    }//GEN-LAST:event_jBtnTaktFindActionPerformed

    private void jMnuTaktFindActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMnuTaktFindActionPerformed
// TODO adicione seu código de manipulação aqui:
        taktFind();
    }//GEN-LAST:event_jMnuTaktFindActionPerformed

    private void jBtnFindActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnFindActionPerformed
// TODO adicione seu código de manipulação aqui:
        find();
    }//GEN-LAST:event_jBtnFindActionPerformed

    private void jTxtCodigoFindKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTxtCodigoFindKeyTyped
// TODO adicione seu código de manipulação aqui:
        if (!ok){
            evt.consume();
        }
    }//GEN-LAST:event_jTxtCodigoFindKeyTyped

    private void jTxtCodigoFindKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTxtCodigoFindKeyPressed
// TODO adicione seu código de manipulação aqui:
        if (evt.getKeyCode() == KeyEvent.VK_ENTER){
            find();
        }
        int code = evt.getKeyCode();
        if ((code>95 && code<106) || (code==8) || (code>47 && code<58)) {
            ok = true;
        } else {
            ok = false;
        }
    }//GEN-LAST:event_jTxtCodigoFindKeyPressed

    private void jBtnFechar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnFechar1ActionPerformed
// TODO adicione seu código de manipulação aqui:
        jIFraFind.setVisible(false);
        jBandAtivo.setText("Ativo: Menu Principal"); 
    }//GEN-LAST:event_jBtnFechar1ActionPerformed

    private void jBtnFecharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnFecharActionPerformed
// TODO adicione seu código de manipulação aqui:
        jIFraTime.setVisible(false);
        jBandAtivo.setText("Ativo: Menu Principal");        

    }//GEN-LAST:event_jBtnFecharActionPerformed

    private void jTxtCodigoBarraKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTxtCodigoBarraKeyTyped
// TODO add your handling code here:
        if (!ok){
            evt.consume();
        }
    }//GEN-LAST:event_jTxtCodigoBarraKeyTyped

    private void jTxtCodigoBarraKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTxtCodigoBarraKeyPressed
// TODO add your handling code here:
        int code = evt.getKeyCode();
        JValidacao validacao = new JValidacao(jTxtCodigoBarra.getText());
        
        if (evt.getKeyCode() == KeyEvent.VK_ENTER){
            
            if (!validacao.validVazio()){
                
                
                JConexao con = new JConexao();
                con.conect();
                GregorianCalendar grava = new GregorianCalendar();
                
                try{
                    //int setorValido = new JValidacao().validSetor(jTxtCodigoBarra.getText());
                    int setorValido = validacao.validSetor();
                    if (setorValido == 0){
                        
                        mensagem("ERRO: Terceiro Registro da OF!", 1500);
                        
                    } else if (setorValido == 1){
                        
                        con.getStatment().executeUpdate("insert into takttime " +
                                "(codebarof, data, setor) " +
                                "values('"+ jTxtCodigoBarra.getText() +"', '" +
                                grava.getTime() + "', 2)");
                        
                        mensagem("OF Registrada! - Setor 1", 750);
                    } else if (setorValido == 2){
                        
                        con.getStatment().executeUpdate("insert into takttime " +
                                "(codebarof,data,setor) " +
                                "values('"+ jTxtCodigoBarra.getText() +"','" +
                                grava.getTime() + "',4)");
                        
                        mensagem("OF Registrada! - Setor 2", 750);
                    }
                    
                    
                }catch (/*SQLException*/ Exception e) {
                    System.out.println(e.getMessage());
                    JOptionPane.showMessageDialog(null, "ERRO: " + e.getMessage());
                }
                
                con.disconect();
                
                jTxtCodigoBarra.setText("");
                jTxtCodigoBarra.setFocusable(true);
            } else {
                JOptionPane.showMessageDialog(null, "Código de Barras Vazio!");
            }
        }
        
        if ((code>95 && code<106) || (code==8) || (code>47 && code<58)) {
            ok = true;
        } else {
            ok = false;
        }
    }//GEN-LAST:event_jTxtCodigoBarraKeyPressed

    private void jMnuSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMnuSairActionPerformed
// TODO adicione seu código de manipulação aqui:
        exit();
    }//GEN-LAST:event_jMnuSairActionPerformed

    private void jBtnSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnSairActionPerformed
// TODO adicione seu código de manipulação aqui:
        exit();
    }//GEN-LAST:event_jBtnSairActionPerformed

    private void jMnuTaktTimeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMnuTaktTimeActionPerformed
// TODO adicione seu código de manipulação aqui:
        taktTime();
    }//GEN-LAST:event_jMnuTaktTimeActionPerformed

    private void jBtnTaktTimeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnTaktTimeActionPerformed
// TODO adicione seu código de manipulação aqui:
        taktTime();
    }//GEN-LAST:event_jBtnTaktTimeActionPerformed

    public void taktTime(){
        jIFraTime.setVisible(true);
        jBandAtivo.setText("Ativo: TaktTime");        
    }
    
    public void taktFind(){
        jIFraFind.setVisible(true);
        jBandAtivo.setText("Ativo: TaktFind");
    }
    
    public void exit(){
        System.exit(0);
    }
    
    public void mostraData(){
        GregorianCalendar data = new GregorianCalendar();        
        try{	 
            SimpleDateFormat dtFormat = new SimpleDateFormat("dd/MM/yyyy");
            jTxtData.setText(dtFormat.format(data.getTime()));
            jBandDataHora.setText(dtFormat.format(data.getTime()));
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null, e.getMessage());
         }        
    }
    
    public void mostraHora(){
        GregorianCalendar hora = new GregorianCalendar();
        try{	 
            SimpleDateFormat hrFormat = new SimpleDateFormat("HH:mm:ss");
            jTxtHora.setText(hrFormat.format(hora.getTime()));
            jBandDataHora.setText(jBandDataHora.getText() + "  " + jTxtHora.getText());            
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null, e.getMessage());
         }        
    }    
     
    public void mensagem(String msg, int tempo){
        
        JOptionPane pane = new JOptionPane(msg);
        final JDialog dialog = pane.createDialog(null, "TaktTime");
        dialog.setModal(true);             
        Timer timer = new Timer(tempo, new ActionListener() {
            public void actionPerformed(ActionEvent ev) {
                dialog.dispose();                     
            }
        });
        timer.setRepeats(false);
        timer.start();
        dialog.setVisible(true);
        timer.stop();
        
    }
    
    
    public void find(){
        limpaTabela();
        JConexao c = new JConexao();
        c.conect();
        try{
            ResultSet rs = c.getStatment().executeQuery("select * from takttime " +
                    "inner join setores on takttime.setor = setores.id " +
                    "where codebarof = '" + jTxtCodigoFind.getText() + "';");
            
            if(rs.next()){
                while(!rs.isAfterLast()){
                    int idSetor = rs.getInt(4);
                    String data = dtFormat.format(rs.getDate("data"));
                    String hora = hrFormat.format(rs.getTime("data"));
                    String setor = rs.getString("nome");
                            
                    DefaultTableModel tblFind = (DefaultTableModel)jTblFindOF.getModel();
                    tblFind.addRow( new String [] {data,hora,setor});
                    rs.next();
                }
                
            }else {
                JOptionPane.showMessageDialog(null, "OF não Registrada");
            }
            
        }catch (SQLException ex){
            JOptionPane.showMessageDialog(null, "Nâo Foi Possível Realizar a Consulta, Contate o Analista!");
            ex.printStackTrace();
        }
        c.disconect();
        jTxtCodigoFind.selectAll();
    }
    
    public void limpaTabela(){
        DefaultTableModel tblRemove = (DefaultTableModel)jTblFindOF.getModel();
        
        //tblRemove.fireTableRowsDeleted(0,0);
        
        if (tblRemove.getRowCount() > 0){
            for (int i=0;i<=tblRemove.getRowCount();i++){
                tblRemove.removeRow(0);
            }            
        }        
    }
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuTakt().setVisible(true);
            }
        });
    }
    
    // Declaração de variáveis - não modifique//GEN-BEGIN:variables
    private javax.swing.JLabel jBandAtivo;
    private javax.swing.JLabel jBandConexao;
    private javax.swing.JLabel jBandDataHora;
    private javax.swing.JButton jBtnCalcular;
    private javax.swing.JButton jBtnClose;
    private javax.swing.JButton jBtnFechar;
    private javax.swing.JButton jBtnFechar1;
    private javax.swing.JButton jBtnFind;
    private javax.swing.JButton jBtnSair;
    private javax.swing.JButton jBtnTaktFind;
    private javax.swing.JButton jBtnTaktTime;
    private javax.swing.JButton jButton1;
    private javax.swing.JDesktopPane jDesktopPane;
    private javax.swing.JInternalFrame jIFraCalculo;
    private javax.swing.JInternalFrame jIFraFind;
    private javax.swing.JInternalFrame jIFraTime;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLblImage;
    private javax.swing.JLabel jLblImage1;
    private javax.swing.JMenuBar jMenuBar;
    private javax.swing.JMenuItem jMnuAbout;
    private javax.swing.JMenu jMnuAjuda;
    private javax.swing.JMenuItem jMnuCalculo;
    private javax.swing.JMenuItem jMnuEtiquetas;
    private javax.swing.JMenu jMnuFerramentas;
    private javax.swing.JMenu jMnuPrograma;
    private javax.swing.JMenuItem jMnuSair;
    private javax.swing.JMenuItem jMnuTaktFind;
    private javax.swing.JMenuItem jMnuTaktTime;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPnlStatus;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTable jTblFindOF;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JToolBar jToolBar2;
    private javax.swing.JTextField jTxtCodigoBarra;
    private javax.swing.JTextField jTxtCodigoFind;
    private javax.swing.JTextField jTxtData;
    private javax.swing.JTextField jTxtDemanda;
    private javax.swing.JTextField jTxtHora;
    private javax.swing.JTextField jTxtHora1;
    private javax.swing.JTextField jTxtTaktPadrao;
    private javax.swing.JTextField jTxtTaktTime;
    // Fim da declaração de variáveis//GEN-END:variables
    
}
